# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kRCjmQ7NjVoqdNbg8UPc_w_7dUSwuqXb
"""

# app.py
!pip install -q streamlit
import streamlit as st
from gspread_dataframe import set_with_dataframe
from google.colab import files, drive, auth
import io
import gspread as gd
import pandas as pd
from google.auth import default
import warnings
import logging

def main():
    # Mount Google Drive and authenticate user
    drive.mount('/content/drive')
    auth.authenticate_user()
    creds, _ = default()
    gc = gd.authorize(creds)
    logging.getLogger().setLevel(logging.CRITICAL)

    # Create Streamlit app
    st.title("Data Marketplace Update")

    # SHOPEE
    st.header("SHOPEE Data Upload")
    shopee_file = st.file_uploader("Upload SHOPEE Excel file", type=["xlsx"])
    if shopee_file:
        set_with_dataframe(gc.open('MACS - DATA MARKETPLACE UPDATE').worksheet('SHOPEE'),
                           pd.read_excel(shopee_file, sheet_name='orders'),
                           include_column_header=True)
        st.success("SHOPEE data uploaded successfully!")

    # TOKOPEDIA
    st.header("TOKOPEDIA Data Upload")
    tokopedia_file = st.file_uploader("Upload TOKOPEDIA Excel file", type=["xlsx"])
    if tokopedia_file:
        set_with_dataframe(gc.open('MACS - DATA MARKETPLACE UPDATE').worksheet('TOKOPEDIA'),
                           pd.read_excel(tokopedia_file, sheet_name='Laporan Penjualan', skiprows=4, usecols="A:AP"),
                           include_column_header=True)
        st.success("TOKOPEDIA data uploaded successfully!")

    # LAZADA
    st.header("LAZADA Data Upload")
    lazada_file = st.file_uploader("Upload LAZADA Excel file", type=["xlsx"])
    if lazada_file:
        set_with_dataframe(gc.open('MACS - DATA MARKETPLACE UPDATE').worksheet('LAZADA'),
                           pd.read_excel(lazada_file, sheet_name='sheet1'),
                           include_column_header=True)
        st.success("LAZADA data uploaded successfully!")

if __name__ == "__main__":
    main()